FROM java:7-jre

ENV CF_HOME /opt/ColdFusion
ENV WEBROOT /var/www
ENV PATH $CF_HOME/cfusion/bin:$PATH
WORKDIR $CF_HOME

ENV ACF_LIBS_URL https://e05ac1a30afa93e642cc134035af0ab2babf7ac5.googledrive.com/host/0B-P1-Q_5RyjoMHZ2ZEtieXZjZG8/AdobeColdFusion/11/ColdFusion_exp_11_WWEJ_linux64_041514.zip

# Download and delete zip in one step to avoid committing the installer in a FS layer
RUN wget -nv $ACF_LIBS_URL -O /opt/ACF11.zip && \
	cd /opt && \
	unzip ACF11.zip && \
	rm -rf /opt/ACF11.zip

# Copy the default directories to our new webroot
# RUN cp -r $CF_HOME/cfusion/wwwroot/CFIDE $WEBROOT/ && \
#	cp -r $CF_HOME/cfusion/wwwroot/WEB-INF $WEBROOT/

EXPOSE 8500

CMD ["set","-e"]
CMD ["coldfusion", "start"]