FROM tomcat:8-jre8
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

ENV LUCEE_JARS_URL http://snapshot.lucee.org/rest/update/provider/loader/5.0.0.244-SNAPSHOT

# Download core JAR, and delete it in one step to avoid committing the installer in a FS layer
RUN wget -nv $LUCEE_JARS_URL -O /root/lucee.jar && \
	mkdir -p $CATALINA_HOME/lucee && \
	cp /root/lucee.jar $CATALINA_HOME/lucee/lucee.jar && \
	rm -rf /root/lucee.jar

# Delete the default Tomcat webapps so they aren't deployed at startup
RUN rm -rf $CATALINA_HOME/webapps/*

# Set Tomcat config to load Lucee
COPY Lucee5/catalina.properties Lucee5/server.xml Lucee5/web.xml $CATALINA_HOME/conf/

# Custom setenv.sh to load Lucee
COPY Lucee5/setenv.sh $CATALINA_HOME/bin/
RUN chmod a+x $CATALINA_HOME/bin/setenv.sh

# Create Lucee configs
COPY Lucee5/lucee-server.xml /opt/lucee/server/lucee-server/context/lucee-server.xml
COPY Lucee5/lucee-web.xml.cfm /opt/lucee/web/lucee-web.xml.cfm

EXPOSE 8088

CMD ["mkdir","/var/www/tests/results/lucee5"]
CMD ["catalina.sh", "run"]